version: "3"

tasks:
  build:
    cmds:
      - docker build . -t ghcr.io/sandbox-pokhara/journal-discord-bot

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/journal-discord-bot

  deploy:
    cmds:
      - ssh andreu-ovh -t "docker service update --with-registry-auth --image ghcr.io/sandbox-pokhara/journal-discord-bot journal_discord_bot"
