[tool.ruff]
src = ["./backend"]
exclude = ["./backend/**/migrations/"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ty.environment]
root = ["./backend"]

[tool.ty.src]
exclude = ["./backend/**/migrations/"]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
executionEnvironments = [{ root = "backend" }]
include = ["backend"]
exclude = ["**/venv", "**/migrations"]
