[tool.isort]
src_paths = ["backend"]
skip_glob = ["*/migrations/*"]

line_length = 79
force_single_line = true

[tool.black]
line-length = 79
preview = true
enable-unstable-feature = ["string_processing"]
extend-exclude = "migrations"

[tool.pyright]
venvPath = "."
venv = "venv"
typeCheckingMode = "strict"
executionEnvironments = [{ root = "backend" }]
include = ["backend"]
exclude = ["**/venv", "**/migrations"]
