[tool.isort]
src_paths = ["backend", "discord_bot"]
skip_glob = ["*/migrations/*"]

line_length = 79
force_single_line = true

[tool.black]
line-length = 79
preview = true
extend-exclude = "migrations"


[tool.pyright]
typeCheckingMode = "strict"
executionEnvironments = [{ root = "backend" }, { root = "discord_bot" }]
include = ["backend", "discord_bot"]
exclude = ["**/venv", "**/migrations"]
