version: "3"

tasks:
  build:
    cmds:
      - docker build backend -t ghcr.io/sandbox-pokhara/journal

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/journal

  deploy-backend:
    cmds:
      - ssh andreu-ovh -t "docker service update --with-registry-auth --image ghcr.io/sandbox-pokhara/journal journal_backend"

  deploy-discord-bot:
    cmds:
      - ssh andreu-ovh -t "docker service update --with-registry-auth --image ghcr.io/sandbox-pokhara/journal journal_discord_bot"
