version: "3"

tasks:
  build:
    cmds:
      - docker build backend -t ghcr.io/sandbox-pokhara/journal

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/journal

  deploy:
    cmds:
      - ssh ubuntu@51.178.66.98 -t "docker stack deploy -c journal/docker-compose.yml --with-registry-auth journal --detach=false"
