version: "3"

tasks:
  run:
    cmds:
      - docker run --net host ghcr.io/sandbox-pokhara/journal

  run-db:
    cmds:
      - docker run --net host -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=jourmal postgres

  build:
    cmds:
      - docker build . -t ghcr.io/sandbox-pokhara/journal

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/journal
