version: "3"

tasks:
  build:
    cmds:
      - docker build . -t ghcr.io/sandbox-pokhara/journal-backend

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/journal-backend

  deploy-backend:
    cmds:
      - ssh andreu-ovh -t "docker service update --with-registry-auth --image ghcr.io/sandbox-pokhara/journal-backend journal_backend"

  deploy-discord-bot:
    cmds:
      - ssh andreu-ovh -t "docker service update --with-registry-auth --image ghcr.io/sandbox-pokhara/journal-backend journal_discord_bot"
