# Generated by Django 5.1.5 on 2025-02-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_checkin_message_absence_holiday_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="journal",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
