# Generated by Django 5.1.5 on 2025-02-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_absence_message_alter_checkin_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="is_break",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="absence",
            name="is_partial",
            field=models.BooleanField(default=False),
        ),
    ]
