# Generated by Django 5.1.5 on 2025-02-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_absence_is_break_absence_is_partial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="absence",
            name="is_break",
        ),
        migrations.RemoveField(
            model_name="absence",
            name="is_partial",
        ),
    ]
