# Generated by Django 5.2.4 on 2025-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_userdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="is_paid",
            field=models.BooleanField(default=True),
        ),
    ]
